apiVersion: v1
entries:
  bpui:
  - apiVersion: v1
    appVersion: V.0.10.2
    created: "2020-05-29T13:13:30.564655766Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: 3a1d360ea234cad1e30a4b23d7cdc8020cee89ca305d640971b24af3d6a77f43
    home: pan.conduction.nl
    icon: pan.conduction.nl
    name: bpui
    urls:
    - bpui-0.1.0.tgz
    version: 0.1.0
  pan:
  - apiVersion: v1
    appVersion: V.0.1
    created: "2020-05-29T13:13:30.569121166Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: edccd6569f07c6bea1cd625597985921418c6dc89aa5534253789f49848a6467
    home: pan.conduction.nl
    icon: pan.conduction.nl
    name: pan
    urls:
    - pan-0.1.0.tgz
    version: 0.1.0
generated: "2020-05-29T13:13:30.558064366Z"
