apiVersion: v1
entries:
  bpui:
  - apiVersion: v1
    appVersion: V.0.10.5
    created: "2020-06-22T12:31:11.141965333Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: f2d6260db2c4515ca8fc73a6745b1c21589a6824a6dba2b773bc8f48da411f4c
    home: pan.conduction.nl
    icon: pan.conduction.nl
    name: bpui
    urls:
    - bpui-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-22T12:31:11.136719233Z"
