apiVersion: v1
entries:
  bpui:
  - apiVersion: v1
    appVersion: V.0.10.2
    created: "2020-06-02T07:54:04.4991322Z"
    description: '&#039;Naast deze JSON rest API is er ook een [graphql](/graphql)
      interface beschikbaar.&#039;'
    digest: e5b3ef7d08c682ca4f7822a8190a1df868ab3a49f35b82ddcfed025c015f96a3
    home: pan.conduction.nl
    icon: pan.conduction.nl
    name: bpui
    urls:
    - bpui-0.1.0.tgz
    version: 0.1.0
generated: "2020-06-02T07:54:04.4274248Z"
