{{- if .Values.settings.loadbalancerEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.settings.name }}-api-loadbalancer
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.settings.name }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port: 443
      targetPort: 80
      name: https
{{- end }}
