apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
    name: {{ include "name" . }}-{{ .Values.settings.env }}-letsencrypt
    labels:
        app.kubernetes.io/name: {{ include "name" . }}
        app.kubernetes.io/part-of: {{ include "name" . }}
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  acme:
    email: {{ .Values.settings.email }}
    http01: {}
    privateKeySecretRef:
      name: letsencrypt-private-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - selector: {}
      http01:
        ingress:
          class: nginx
