{{- if .Values.varnish.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.settings.name }}-varnish
  labels:
    app.kubernetes.io/name: {{ .Values.settings.name }}-varnish
    app.kubernetes.io/part-of: {{ .Values.settings.name }}
    helm.sh/chart: {{ include "chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.settings.name }}-varnish
  replicas: {{ .Values.varnish.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.settings.name }}-varnish
        helm.sh/chart: {{ include "chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: {{ .Values.settings.name }}-varnish
          image: "{{ .Values.settings.registryBase }}/{{ .Values.settings.projectName }}-varnish:{{ .Values.settings.env }}"
          imagePullPolicy: {{ .Values.settings.pullPolicy }}
          env:
            - name: BACKENDS
              value: {{ .Values.settings.name }}-php
          #command: ["varnishd"]
          #args: ["-F", "-f", "/usr/local/etc/varnish/default.vcl", "-p", "http_resp_hdr_len=65536", "-p", "http_resp_size=98304"]
          ports:
            - containerPort: 80
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
{{- end -}}
